//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

namespace Envio
{



    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.esocial.gov.br/schema/lote/eventos/envio/v1_1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.esocial.gov.br/schema/lote/eventos/envio/v1_1_0", IsNullable = false)]
    public partial class eSocial
    {

        private eSocialEnvioLoteEventos envioLoteEventosField;

        /// <remarks/>
        public eSocialEnvioLoteEventos envioLoteEventos
        {
            get
            {
                return this.envioLoteEventosField;
            }
            set
            {
                this.envioLoteEventosField = value;
            }
        }

        public eSocial()
        {
            envioLoteEventos = new Envio.eSocialEnvioLoteEventos();
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.esocial.gov.br/schema/lote/eventos/envio/v1_1_0")]
    public partial class eSocialEnvioLoteEventos
    {

        private TIdeEmpregador ideEmpregadorField;

        private TIdeTransmissor ideTransmissorField;

        private eSocialEnvioLoteEventosEventos eventosField;

        private int grupoField;

        /// <remarks/>
        public TIdeEmpregador ideEmpregador
        {
            get
            {
                return this.ideEmpregadorField;
            }
            set
            {
                this.ideEmpregadorField = value;
            }
        }

        /// <remarks/>
        public TIdeTransmissor ideTransmissor
        {
            get
            {
                return this.ideTransmissorField;
            }
            set
            {
                this.ideTransmissorField = value;
            }
        }

        /// <remarks/>
        public eSocialEnvioLoteEventosEventos eventos
        {
            get
            {
                return this.eventosField;
            }
            set
            {
                this.eventosField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int grupo
        {
            get
            {
                return this.grupoField;
            }
            set
            {
                this.grupoField = value;
            }
        }

        public eSocialEnvioLoteEventos()
        {
            ideEmpregador = new Envio.TIdeEmpregador();
            ideTransmissor = new Envio.TIdeTransmissor();
            eventos = new eSocialEnvioLoteEventosEventos();
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.esocial.gov.br/schema/lote/eventos/envio/v1_1_0")]
    public partial class TIdeEmpregador
    {

        private int tpInscField;

        private string nrInscField;

        /// <remarks/>
        public int tpInsc
        {
            get
            {
                return this.tpInscField;
            }
            set
            {
                this.tpInscField = value;
            }
        }

        /// <remarks/>
        public string nrInsc
        {
            get
            {
                return this.nrInscField;
            }
            set
            {
                this.nrInscField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.esocial.gov.br/schema/lote/eventos/envio/v1_1_0")]
    public partial class TArquivoEsocial
    {

        private System.Xml.XmlElement anyField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.esocial.gov.br/schema/lote/eventos/envio/v1_1_0")]
    public partial class TIdeTransmissor
    {

        private int tpInscField;

        private string nrInscField;

        /// <remarks/>
        public int tpInsc
        {
            get
            {
                return this.tpInscField;
            }
            set
            {
                this.tpInscField = value;
            }
        }

        /// <remarks/>
        public string nrInsc
        {
            get
            {
                return this.nrInscField;
            }
            set
            {
                this.nrInscField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.esocial.gov.br/schema/lote/eventos/envio/v1_1_0")]
    public partial class eSocialEnvioLoteEventosEventos
    {

        private TArquivoEsocial[] eventoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("evento")]
        public TArquivoEsocial[] evento
        {
            get
            {
                return this.eventoField;
            }
            set
            {
                this.eventoField = value;
            }
        }
    }
}