//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Retorno
{



    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.esocial.gov.br/schema/lote/eventos/envio/retornoEnvio/v1_1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.esocial.gov.br/schema/lote/eventos/envio/retornoEnvio/v1_1_0", IsNullable = false)]
    public partial class eSocial
    {

        private eSocialRetornoEnvioLoteEventos retornoEnvioLoteEventosField;

        /// <remarks/>
        public eSocialRetornoEnvioLoteEventos retornoEnvioLoteEventos
        {
            get
            {
                return this.retornoEnvioLoteEventosField;
            }
            set
            {
                this.retornoEnvioLoteEventosField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.esocial.gov.br/schema/lote/eventos/envio/retornoEnvio/v1_1_0")]
    public partial class eSocialRetornoEnvioLoteEventos
    {

        private TIdeEmpregador ideEmpregadorField;

        private TIdeTransmissor ideTransmissorField;

        private TStatus statusField;

        private TDadosRecepcao dadosRecepcaoLoteField;

        /// <remarks/>
        public TIdeEmpregador ideEmpregador
        {
            get
            {
                return this.ideEmpregadorField;
            }
            set
            {
                this.ideEmpregadorField = value;
            }
        }

        /// <remarks/>
        public TIdeTransmissor ideTransmissor
        {
            get
            {
                return this.ideTransmissorField;
            }
            set
            {
                this.ideTransmissorField = value;
            }
        }

        /// <remarks/>
        public TStatus status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        public TDadosRecepcao dadosRecepcaoLote
        {
            get
            {
                return this.dadosRecepcaoLoteField;
            }
            set
            {
                this.dadosRecepcaoLoteField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.esocial.gov.br/schema/lote/eventos/envio/retornoEnvio/v1_1_0")]
    public partial class TIdeEmpregador
    {

        private int tpInscField;

        private string nrInscField;

        /// <remarks/>
        public int tpInsc
        {
            get
            {
                return this.tpInscField;
            }
            set
            {
                this.tpInscField = value;
            }
        }

        /// <remarks/>
        public string nrInsc
        {
            get
            {
                return this.nrInscField;
            }
            set
            {
                this.nrInscField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.esocial.gov.br/schema/lote/eventos/envio/retornoEnvio/v1_1_0")]
    public partial class TDadosRecepcao
    {

        private System.DateTime dhRecepcaoField;

        private string versaoAplicativoRecepcaoField;

        private string protocoloEnvioField;

        /// <remarks/>
        public System.DateTime dhRecepcao
        {
            get
            {
                return this.dhRecepcaoField;
            }
            set
            {
                this.dhRecepcaoField = value;
            }
        }

        /// <remarks/>
        public string versaoAplicativoRecepcao
        {
            get
            {
                return this.versaoAplicativoRecepcaoField;
            }
            set
            {
                this.versaoAplicativoRecepcaoField = value;
            }
        }

        /// <remarks/>
        public string protocoloEnvio
        {
            get
            {
                return this.protocoloEnvioField;
            }
            set
            {
                this.protocoloEnvioField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.esocial.gov.br/schema/lote/eventos/envio/retornoEnvio/v1_1_0")]
    public partial class TStatus
    {

        private int cdRespostaField;

        private string descRespostaField;

        private TOcorrenciasOcorrencia[] ocorrenciasField;

        /// <remarks/>
        public int cdResposta
        {
            get
            {
                return this.cdRespostaField;
            }
            set
            {
                this.cdRespostaField = value;
            }
        }

        /// <remarks/>
        public string descResposta
        {
            get
            {
                return this.descRespostaField;
            }
            set
            {
                this.descRespostaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ocorrencia", IsNullable = false)]
        public TOcorrenciasOcorrencia[] ocorrencias
        {
            get
            {
                return this.ocorrenciasField;
            }
            set
            {
                this.ocorrenciasField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.esocial.gov.br/schema/lote/eventos/envio/retornoEnvio/v1_1_0")]
    public partial class TOcorrenciasOcorrencia
    {

        private int codigoField;

        private string descricaoField;

        private byte tipoField;

        private string localizacaoField;

        /// <remarks/>
        public int codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }

        /// <remarks/>
        public string descricao
        {
            get
            {
                return this.descricaoField;
            }
            set
            {
                this.descricaoField = value;
            }
        }

        /// <remarks/>
        public byte tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }

        /// <remarks/>
        public string localizacao
        {
            get
            {
                return this.localizacaoField;
            }
            set
            {
                this.localizacaoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.esocial.gov.br/schema/lote/eventos/envio/retornoEnvio/v1_1_0")]
    public partial class TIdeTransmissor
    {

        private int tpInscField;

        private string nrInscField;

        /// <remarks/>
        public int tpInsc
        {
            get
            {
                return this.tpInscField;
            }
            set
            {
                this.tpInscField = value;
            }
        }

        /// <remarks/>
        public string nrInsc
        {
            get
            {
                return this.nrInscField;
            }
            set
            {
                this.nrInscField = value;
            }
        }
    }
}